apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: onetouch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pankajdevops2403/backend:36
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "root"
        - name: MYSQL_DB
          value: "mydb"
