apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  namespace: onetouch
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  service:
    port: 3000
    targetPort: 3000
    gateways:
    - onetouch-gateway
    hosts:
    - backend.onetouch.local
  analysis:
    interval: 30s
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 500
      interval: 1m
