name: Demo CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Marketplace se liya: checkout action
      - name: Checkout repo
        uses: actions/checkout@v4
  
  

          
    
  
