name: Demo CI

on: push
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Marketplace se liya: checkout action
      - name: Checkout repo
        uses: actions/checkout@v4

      # # Marketplace se liya: setup buildx
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # # Marketplace se liya: docker login
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # # Marketplace se liya: docker build-push
      # - name: Build & Push image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo:${{ github.run_number }}
  
  

          
    
  
